### ISSUE TITLE
How to select old() input value after postback using @input_maker_create?

### ISSUE THREAD

**Issue by thinkstylestudio** [YABhq/FormMaker#11]
Given this: 
```
@input_maker_create('product', ['type' => 'select', 'options' => $productDropDownListItems])
```
Where `$productDropDownListItems` outputs an array of options 

```
[
1 => 'Load',
5 => 'Labels'
]
```
If the user selects labels... how do tell the `input_maker_create` to make `value=5` as the selected value? I haven't found any examples or any docs referencing this specifically. 

Thanks in advance!

**Comment by mlantz** [comment]
Hmm, the InputMaker is designed to work with objects, so after the config array you could do something like:

`(object) old()` 

This sets the old array as an object and should contain the key => value of your input

**Comment by amirulfirdaus** [comment]
Can you help me on multiple select?

The code below didn't select anything:

```
 @input_maker_create('tags', [
       'type' => 'relationship',
       'model' => 'App\Models\Tag', 
       'custom' => 'multiple name="tags[]"',
       'option' => $article->tags,
       'label' => 'name',
       'value' => 'id'
])
```

**Comment by mlantz** [comment]
Hey @amirulfirdaus turns out there was a bug. I've made a fix so now it would look like:

```
 @input_maker_create('tags[]', [
       'type' => 'relationship',
       'model' => 'App\Models\Tag', 
       'custom' => 'multiple',
       'label' => 'name',
       'value' => 'id'
])
```

I'll release the update later today

**Comment by amirulfirdaus** [comment]
Yes, that's what I thought. I did `$article->tags->pluck('id', 'name')`. Turns out it only select the first value. Thanks for fixing this.
