### ISSUE TITLE
using the formArray() function. how does one set a default or initial entered value of a field

### ISSUE THREAD

**Issue by thinkstylestudio** [YABhq/FormMaker#12]
using the `formArray()` function. how does one set a default or initial entered value of a field? 

```
formArray([
...
  birth_date'         => [
     'type'   => 'input',
     'objectValue' => 'sample Test' // I would have expected 'value' => 'default set value' 
  ],
...
]);
```
`objectValue` does not seem to add a `"value"` to the generated field input.

**Comment by mlantz** [comment]
Hey so I guess it turns out I never accommodated for that and the fromArray can only do things like 
```
'name' => 'string',
'age' => 'number',
```

But if you want to add set values on things I've added the ability to set the value using the `@input_maker_create('name', ['type' => 'string', 'default_value' => 'awesome'])`

**Comment by thinkstylestudio** [comment]
Awesome! Thanks.

-- 
Theron S
Sent with Airmail

On January 24, 2017 at 2:10:15 PM, Matt Lantz (notifications@github.com)
wrote:

Hey so I guess it turns out I never accommodated for that and the fromArray
can only do things like

'name' => 'string',
'age' => 'number',

But if you want to add set values on things I've added the ability to set
the value using the @input_maker_create('name', ['type' => 'string',
'default_value' => 'awesome'])

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/YABhq/FormMaker/issues/12#issuecomment-274955488>, or mute
the thread
