### ISSUE TITLE
error with @input_maker_create

### ISSUE THREAD

**Issue by ashish64** [YABhq/FormMaker#13]
Im working with laracogs.
here is the error im getting:
snippet im using::
`@input_maker_create('meta[phone]', ['type' => 'string'], $user)`
result im getting::
`<input id="Meta[phone]" class="form-control" name="meta[phone]" value="{" id":1,"user_id":1,"phone":null,"is_active":1,"activation_token":"59afc4ace32e7a6b8b3d8e69d1659f05","marketing":0,"terms_and_cond":1,"created_at":"2017-01-19="" 11:47:44","updated_at":"2017-01-19="" 11:47:44"}"="" placeholder="Meta Phone" type="text">`

As you can see, I want the value from phone field from meta table to populate the table, instead chaotic is going on in here!!

**Comment by mlantz** [comment]
Hey I found the problem, its due to the field being a null value, I have a fix I'll be pushing this week
