### ISSUE TITLE
old() value failing on nested array

### ISSUE THREAD

**Issue by vool** [YABhq/FormMaker#15]
Old values are not been retained on nested arrays / forms 

I could be wrong but this seems to be due to the fact that the method refineConfigs() seems to be checking for 'name' but the nested array will be array['name'] 

 $inputConfig['inputs'][$name]

This can be recreated by running a fresh laravel install and laracogs starter.
On /user/settings add a phone number and delete the name or email and save.
The phone number will be lost.

**Comment by mlantz** [comment]
The name and email are both required by default so it would fail to work with the nested values. If I test the latest builds of everything with the phone number being added or removed everything works fine
