### ISSUE TITLE
Using a custom theme

### ISSUE THREAD

**Issue by Rav23** [YABhq/FormMaker#18]
Hi there guys, 

I bought a bootstrap theme and have been using it with Laracogs. I recently came across the select element and can't seem to generate a select element that uses the theme within blade. 

This is because when I use @foreach directive I can't seem to be able to create a roles selection. I can only achieve it using the default installation and normal bootstrap.

Regards

**Comment by mlantz** [comment]
Are you trying to make the input individually or with the form maker? Here are two examples:

`FormMaker::fromTable('users', ['roles' => ['type' => 'select', 'class' => 'something-different', 'options' => $options]])`

Or

`InputMaker::create('roles', ['type' => 'select', 'options' => $options], null, 'something-different')`

**Comment by mlantz** [comment]
I've improved some of the customizability of the FormMaker parts - in the config you'll see:

```   'form-class' => 'form-control',
        'group-class' => 'form-group',
        'error-class' => 'has-error',
        'label-class' => 'control-label',```

which can be used by default - then for custom inputs you can pass whatever custom classes are needed :)

**Comment by Rav23** [comment]
Thank You so much! Laracogs is awesome.
