### ISSUE TITLE
Limiter on input maker models

### ISSUE THREAD

**Issue by absalomedia** [YABhq/FormMaker#2]
Currently Laracogs eager loads the model of whatever relationship it's presented with. i.e.
```
@input_maker_label('Store')
@input_maker_create('stores', ['type' => 'relationship', 'model' => 'App\Repositories\Store\Store', 'label' => 'name', 'value' => 'id'], $user)
```

I'm looking for a way to limit what's loaded into the model somehow. Any ideas on how to go about this?

**Comment by mlantz** [comment]
When you say limit do you mean you'd like to be able to have a set of logic which limits the return of values? For example based on permission?

**Comment by absalomedia** [comment]
I need some way of passing in equivalent of:
`DB::table('table')->where('var','=',1)->get(); `
into the input_maker_model for relationships instead of eager loading the entire class.

**Comment by mlantz** [comment]
Ok, I've added that in, will release sometime today :)

**Comment by absalomedia** [comment]
Works as planned. Thanks for this
