### ISSUE TITLE
Timestamps that are auto converted to Carbon, get error

### ISSUE THREAD

**Issue by arturmamedov** [YABhq/FormMaker#4]
In my Model i add the proprety `$dates` for convert automatically the my timestamps to Carbon object and after this i get a error.

```php
protected $dates = ['created_at', 'updated_at', 'deleted_at', 'from_ts', 'to_ts'];
```
What i'm get:
`
ErrorException in InputCalibrator.php line 56: Object of class Carbon\Carbon could not be converted to int (View: D:\serverpath\dev2016\yabhq-laracogs\www\laracogs\resources\views\pricelist\periods\edit.blade.php)
`

**Comment by mlantz** [comment]
I suspect its a conflict of the database reader and the date type casting. Technically the form will be based on the table column types and thusly if you're typecasting them it could conflict, I suggest making a custom config for the form

**Comment by arturmamedov** [comment]
You mean something like this:
```php
@form_maker_object($period, 
$columns = ['site_id', 'parent_id', 'name', 'description', 
    'from_ts' => ['type' => 'text'], 
    'to_ts' => ['type' => 'text'], 
    'position'], 
$view = null, 
$class = 'form-control', 
$populated = true, 
$reformatted = false, 
$idAndTimestamps = false)
```

Sorry but i can't find how, this one not work for me. Can you tell me where is in the documentation? Many Thanks.

**Comment by mlantz** [comment]
Hey so I got this fixed, just pull in the latest release
