### ISSUE TITLE
Checkbox Value

### ISSUE THREAD

**Issue by vool** [YABhq/FormMaker#5]
Hello,

I might be missing something obvious here but i can't seem to get a 'value' for a checkbox using InputMaker 

eg.

``  {{ Form::checkbox('published', true) }}``

will give me 

`` <input name="published" type="checkbox" value="1">``

while 

`` @input_maker_create('published', ['type' => 'checkbox'], $foo) ``

outputs

`` <input  id="Published"  type="checkbox" name="published">     ``

**Comment by mlantz** [comment]
The checkbox will track whether or not the box has been checked but if you want to set a specific value you can use:

`@input_maker_create('published', ['type' => 'checkbox', 'custom' => 'value="on"'], $foo)`

**Comment by vool** [comment]
ah, thanks
