### ISSUE TITLE
v1.0.8 of FormMaker is broken

### ISSUE THREAD

**Issue by gregolai** [YABhq/FormMaker#9]
v1.0.8 of FormMaker has a syntax error on line 70, where $connection is misspelled when passed in as an argument. It's fixed in origin/master, but when composer requires FormMaker as a dependency for laracogs, it asks for the broken version. I can't submit a pull requests for tag changes, so it'll have to be fixed by YABhq, something like this:

![image](https://cloud.githubusercontent.com/assets/936372/20388132/8578aa0e-ac91-11e6-8b17-03d0400734f8.png)

**Comment by mlantz** [comment]
I must have got the tagging out of alignment, I'll fix the tag so that its correct with the master branch, thanks
